# Generated by Django 3.0.3 on 2022-06-06 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_ram', models.TextField()),
                ('mobile_cpu', models.TextField()),
                ('mobile_storage', models.TextField()),
                ('mobile_color', models.TextField()),
                ('mobile_other_features', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('mobile_name', models.CharField(max_length=150)),
                ('mobile_img', models.ImageField(upload_to='BuyPhones_images')),
                ('mobile_desc', models.TextField()),
                ('date', models.DateField()),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BuyPhonesApp.Specs')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('user_name', models.CharField(max_length=150)),
                ('user_comments', models.TextField(max_length=300)),
                ('date', models.DateField()),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BuyPhonesApp.Mobile')),
            ],
        ),
    ]
