# Generated by Django 4.0.3 on 2022-05-04 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter_menu', models.TextField()),
                ('main_course', models.TextField()),
                ('desert', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('title', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='restaurant_images')),
                ('desc', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=16)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('date', models.DateField()),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='NearByRestaurantApp.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('user_name', models.CharField(max_length=150)),
                ('comments', models.TextField(max_length=300)),
                ('date', models.DateField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='NearByRestaurantApp.restaurant')),
            ],
        ),
    ]
